# Paramètres de connection à la base de données, en fonction de l'environnement de developpement
dev:
    db_name: vacherot
    db_host: dev.etudiant-eemi.com
    db_user: vacherot
    db_pass: 882077

test:
    db_name: vacherot
    db_host: dev.etudiant-eemi.com
    db_user: vacherot
    db_pass: 882077

prod:
    db_name: vacherot
    db_host: dev.etudiant-eemi.com
    db_user: vacherot
    db_pass: 882077
